CARES_VERSION = "3be1924221e1326df520f8498d704a5c4c8d0cce" # Jun 16, 2017 (1.13.0)

# protobuf & grpc rules
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.8.1"
)

# Load language-specific dependencies
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories(
    overrides = {
        "com_github_cares_cares": {
            "rule": "new_http_archive",
            "url": "https://github.com/c-ares/c-ares/archive/%s.zip" % CARES_VERSION,
            "sha256": "932bf7e593d4683fce44fd26920f27d4f0c229113338e4f6d351e35d4d7c7a39",
            "strip_prefix": "c-ares-" + CARES_VERSION,
            "build_file": "cares.BUILD",
        }
    }
)

# apple rules
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.6.0",
)
load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)
apple_rules_dependencies()
