// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#include "NativeRegisterUserCallback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeRegisterUserCallback::NativeRegisterUserCallback() : ::djinni::JniInterface<::cjlogin::RegisterUserCallback, NativeRegisterUserCallback>("com/jeason/cjlogin/RegisterUserCallback$CppProxy") {}

NativeRegisterUserCallback::~NativeRegisterUserCallback() = default;


CJNIEXPORT void JNICALL Java_com_jeason_cjlogin_RegisterUserCallback_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::cjlogin::RegisterUserCallback>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_jeason_cjlogin_RegisterUserCallback_00024CppProxy_native_1complete(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_errcode, jstring j_errmsg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::cjlogin::RegisterUserCallback>(nativeRef);
        ref->complete(::djinni::I32::toCpp(jniEnv, j_errcode),
                      ::djinni::String::toCpp(jniEnv, j_errmsg));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
