// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#pragma once

#include "djinni_support.hpp"
#include "registerUserCallback.hpp"

namespace djinni_generated {

class NativeRegisterUserCallback final : ::djinni::JniInterface<::cjlogin::RegisterUserCallback, NativeRegisterUserCallback> {
public:
    using CppType = std::shared_ptr<::cjlogin::RegisterUserCallback>;
    using CppOptType = std::shared_ptr<::cjlogin::RegisterUserCallback>;
    using JniType = jobject;

    using Boxed = NativeRegisterUserCallback;

    ~NativeRegisterUserCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRegisterUserCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRegisterUserCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRegisterUserCallback();
    friend ::djinni::JniClass<NativeRegisterUserCallback>;
    friend ::djinni::JniInterface<::cjlogin::RegisterUserCallback, NativeRegisterUserCallback>;

};

}  // namespace djinni_generated
