# protobuf & grpc rules
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.8.1"
)

# Load language-specific dependencies
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories(
    excludes = [
        "boringssl"
    ],
    overrides = {
        "libssl": {
            "rule": "bind",
            "actual": "@com_github_openssl_wrap//:dep_libs"
        }
    }
)

# hiredis
new_git_repository(
    name = "com_redis_hiredis",
    remote = "https://github.com/redis/hiredis",
    tag = "v0.13.3",
    build_file = "BUILD.hiredis"
)

# md5
new_git_repository(
    name = "com_github_md5",
    remote = "https://github.com/JieweiWei/md5",
    commit = "30774d0c9ecf82fb003fc15978b1f21bc85858f7",
    build_file = "BUILD.md5"
)

#glog
http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "6e16c8bc91b1310a44f3965e616383dbda48f83e8c1eaa2370a215057b00cabe",
    strip_prefix = "gflags-77592648e3f3be87d6c7123eb81cbad75f9aef5a",
    urls = [
        "https://mirror.bazel.build/github.com/gflags/gflags/archive/77592648e3f3be87d6c7123eb81cbad75f9aef5a.tar.gz",
        "https://github.com/gflags/gflags/archive/77592648e3f3be87d6c7123eb81cbad75f9aef5a.tar.gz",
    ],
)

git_repository(
    name = "com_google_glog",
    remote = "https://github.com/google/glog",
    commit = "8d7a107d68c127f3f494bb7807b796c8c5a97a82"
)

# openssl
git_repository(
    name = "com_github_openssl_wrap",
    remote = "https://github.com/lbuchy/bazel-openssl",
    commit = "c700be9ab51d5e869205f69480025cf33b033dc8",
    init_submodules = 1
)

# jwt
new_git_repository(
    name = "com_github_cppjwt",
    remote = "https://github.com/arun11299/cpp-jwt",
    commit = "87dcef903f48a8c33df0bd9658d775d6d5db1918",
    build_file = "BUILD.jwt"
)

# CSPRNG
new_git_repository(
    name = "com_github_csprng",
    remote = "https://github.com/Duthomhas/CSPRNG",
    commit = "8768a94b4b04213c0798b80824a04ae4990e9847",
    build_file = "BUILD.csprng"
)

# bcrypt
new_git_repository(
    name = "com_github_bcrypt",
    remote = "https://github.com/trusch/libbcrypt",
    commit = "2c48ea0cb3e8539996a42ae526f80158e074b97a",
    build_file = "BUILD.bcrypt"
)
