# protobuf & grpc rules
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.8.1"
)

# Load language-specific dependencies
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

new_git_repository(
    name = "com_redis_hiredis",
    remote = "https://github.com/redis/hiredis",
    tag = "v0.13.3",
    build_file = "BUILD.hiredis"
)