// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#include "loginCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CJLoginCallback;

namespace djinni_generated {

class LoginCallback
{
public:
    using CppType = std::shared_ptr<::cjlogin::LoginCallback>;
    using CppOptType = std::shared_ptr<::cjlogin::LoginCallback>;
    using ObjcType = id<CJLoginCallback>;

    using Boxed = LoginCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

