// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#pragma once

#include <cstdint>
#include <string>

namespace cjlogin {

class ConnectCallback {
public:
    virtual ~ConnectCallback() {}

    virtual void complete(int32_t messageType, const std::string & content) = 0;
};

}  // namespace cjlogin
