// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#pragma once

#include <memory>

namespace cjlogin {

class CjLogin {
public:
    virtual ~CjLogin() {}

    static std::shared_ptr<CjLogin> create();
};

}  // namespace cjlogin
