package(default_visibility = ["//visibility:public"])

# proto rules
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
    name = "cj_login_proto",
    protos = ["cj_login.proto"],
    with_grpc = True
)
