// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#include "cj_login.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CJCjLogin;

namespace djinni_generated {

class CjLogin
{
public:
    using CppType = std::shared_ptr<::cjlogin::CjLogin>;
    using CppOptType = std::shared_ptr<::cjlogin::CjLogin>;
    using ObjcType = CJCjLogin*;

    using Boxed = CjLogin;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

