// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>
@class CJCjLogin;


@interface CJCjLogin : NSObject

+ (nullable CJCjLogin *)create;

@end
