// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import "CJCheckLoginCallback+Private.h"
#import "CJCheckLoginCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CJCheckLoginCallback ()

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::CheckLoginCallback>&)cppRef;

@end

@implementation CJCheckLoginCallback {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cjlogin::CheckLoginCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::CheckLoginCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)complete:(int32_t)errcode
          errmsg:(nonnull NSString *)errmsg
      sessionKey:(nonnull NSString *)sessionKey {
    try {
        _cppRefHandle.get()->complete(::djinni::I32::toCpp(errcode),
                                      ::djinni::String::toCpp(errmsg),
                                      ::djinni::String::toCpp(sessionKey));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto CheckLoginCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto CheckLoginCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CJCheckLoginCallback>(cpp);
}

}  // namespace djinni_generated

@end
