// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>
@class CJCheckLoginCallback;
@class CJCjLogin;
@class CJLoginCallback;
@class CJLogoutCallback;
@class CJRegisterUserCallback;


@interface CJCjLogin : NSObject

+ (nullable CJCjLogin *)create;

- (void)registerUser:(nonnull NSString *)userName
            password:(nonnull NSString *)password
                  cb:(nullable CJRegisterUserCallback *)cb;

- (void)login:(nonnull NSString *)userName
     password:(nonnull NSString *)password
           cb:(nullable CJLoginCallback *)cb;

- (void)checkLogin:(nonnull NSString *)userName
       loginTicket:(nonnull NSString *)loginTicket
                cb:(nullable CJCheckLoginCallback *)cb;

- (void)logout:(nonnull NSString *)userName
    sessionKey:(nonnull NSString *)sessionKey
            cb:(nullable CJLogoutCallback *)cb;

@end
