// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import "CJConnectCallback+Private.h"
#import "CJConnectCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CJConnectCallback ()

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::ConnectCallback>&)cppRef;

@end

@implementation CJConnectCallback {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cjlogin::ConnectCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::ConnectCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)complete:(int32_t)messageType
         content:(nonnull NSString *)content {
    try {
        _cppRefHandle.get()->complete(::djinni::I32::toCpp(messageType),
                                      ::djinni::String::toCpp(content));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ConnectCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ConnectCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CJConnectCallback>(cpp);
}

}  // namespace djinni_generated

@end
