// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>


@interface CJConnectCallback : NSObject

- (void)complete:(int32_t)messageType
         content:(nonnull NSString *)content;

@end
