// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import "CJLoginCallback+Private.h"
#import "CJLoginCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CJLoginCallback ()

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::LoginCallback>&)cppRef;

@end

@implementation CJLoginCallback {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cjlogin::LoginCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::LoginCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)complete:(int32_t)errcode
          errmsg:(nonnull NSString *)errmsg
     loginTicket:(nonnull NSString *)loginTicket {
    try {
        _cppRefHandle.get()->complete(::djinni::I32::toCpp(errcode),
                                      ::djinni::String::toCpp(errmsg),
                                      ::djinni::String::toCpp(loginTicket));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto LoginCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto LoginCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CJLoginCallback>(cpp);
}

}  // namespace djinni_generated

@end
