// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>


@interface CJLoginCallback : NSObject

- (void)complete:(int32_t)errcode
          errmsg:(nonnull NSString *)errmsg
     loginTicket:(nonnull NSString *)loginTicket;

@end
