// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>
@class CJCjLogin;
@protocol CJCheckLoginCallback;
@protocol CJConnectCallback;
@protocol CJLoginCallback;
@protocol CJLogoutCallback;
@protocol CJRegisterUserCallback;

enum ErrCode {
    OK = 0,
    SYSTEM_ERROR = -1,
    SYSTEM_SESSION_TIMEOUT = -2,
    SYSTEM_INVALID_PARAM = -3,
    
    REGISTER_ERROR_USERNAME_INVALID = 1001,
    REGISTER_ERROR_USERNAME_EXISTS = 1002,
    REGISTER_ERROR_PWD_INVALID = 1003,
    
    LOGIN_ERROR_USER_NOT_EXISTS = 2001,
    LOGIN_ERROR_PWD_ERROR = 2002,
    
    CHECK_LOGIN_USER_LOGIN_OTHERS = 3001,
    CHECK_LOGIN_TICKET_TIMEOUT = 3003,
};

@interface CJCjLogin : NSObject

+ (nullable CJCjLogin *)create:(nonnull NSString *)server
                    serverCert:(nonnull NSString *)serverCert
                          cert:(nonnull NSString *)cert
                           key:(nonnull NSString *)key
                   sslOverride:(nonnull NSString *)sslOverride;

- (void)registerUser:(nonnull NSString *)userName
            password:(nonnull NSString *)password
                  cb:(nullable id<CJRegisterUserCallback>)cb;

- (void)login:(nonnull NSString *)userName
     password:(nonnull NSString *)password
           cb:(nullable id<CJLoginCallback>)cb;

- (void)checkLogin:(nonnull NSString *)userName
       loginTicket:(nonnull NSString *)loginTicket
                cb:(nullable id<CJCheckLoginCallback>)cb;

- (void)logout:(nonnull NSString *)userName
    sessionKey:(nonnull NSString *)sessionKey
            cb:(nullable id<CJLogoutCallback>)cb;

- (void)connect:(nonnull NSString *)userName
     sessionKey:(nonnull NSString *)sessionKey
             cb:(nullable id<CJConnectCallback>)cb;

@end
