// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#include "registerUserCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CJRegisterUserCallback;

namespace djinni_generated {

class RegisterUserCallback
{
public:
    using CppType = std::shared_ptr<::cjlogin::RegisterUserCallback>;
    using CppOptType = std::shared_ptr<::cjlogin::RegisterUserCallback>;
    using ObjcType = id<CJRegisterUserCallback>;

    using Boxed = RegisterUserCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

