// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import <Foundation/Foundation.h>


@protocol CJRegisterUserCallback

- (void)complete:(int32_t)errcode
          errmsg:(nonnull NSString *)errmsg;

@end
