// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#import "CJRegisterUserCallback+Private.h"
#import "CJRegisterUserCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CJRegisterUserCallbackCppProxy : NSObject<CJRegisterUserCallback>

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::RegisterUserCallback>&)cppRef;

@end

@implementation CJRegisterUserCallbackCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cjlogin::RegisterUserCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cjlogin::RegisterUserCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)complete:(int32_t)errcode
          errmsg:(nonnull NSString *)errmsg {
    try {
        _cppRefHandle.get()->complete(::djinni::I32::toCpp(errcode),
                                      ::djinni::String::toCpp(errmsg));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class RegisterUserCallback::ObjcProxy final
: public ::cjlogin::RegisterUserCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::RegisterUserCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void complete(int32_t c_errcode, const std::string & c_errmsg) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() complete:(::djinni::I32::fromCpp(c_errcode))
                                                        errmsg:(::djinni::String::fromCpp(c_errmsg))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto RegisterUserCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[CJRegisterUserCallbackCppProxy class]]) {
        return ((CJRegisterUserCallbackCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto RegisterUserCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<CJRegisterUserCallbackCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
