// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#pragma once

#include <cstdint>
#include <string>

namespace cjlogin {

class LoginCallback {
public:
    virtual ~LoginCallback() {}

    virtual void complete(int32_t errcode, const std::string & errmsg, const std::string & loginTicket) = 0;
};

}  // namespace cjlogin
