// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

#pragma once

#include <cstdint>
#include <string>

namespace cjlogin {

class LogoutCallback {
public:
    virtual ~LogoutCallback() {}

    virtual void complete(int32_t errcode, const std::string & errmsg) = 0;
};

}  // namespace cjlogin
