// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

package com.jeason.cjlogin;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class CjLogin {
    public abstract void registerUser(String userName, String password, RegisterUserCallback cb);

    public static CjLogin create()
    {
        return CppProxy.create();
    }

    private static final class CppProxy extends CjLogin
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void registerUser(String userName, String password, RegisterUserCallback cb)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_registerUser(this.nativeRef, userName, password, cb);
        }
        private native void native_registerUser(long _nativeRef, String userName, String password, RegisterUserCallback cb);

        public static native CjLogin create();
    }
}
