// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cj-login.djinni

package com.jeason.cjlogin;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class RegisterUserCallback {
    public abstract void complete(int errcode, String errmsg);

    private static final class CppProxy extends RegisterUserCallback
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void complete(int errcode, String errmsg)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_complete(this.nativeRef, errcode, errmsg);
        }
        private native void native_complete(long _nativeRef, int errcode, String errmsg);
    }
}
